---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu-vm
    image: ubuntu:latest
    pre_build_image: true
    command: sleep infinity
  - name: oraclelinux-vm
    image: oraclelinux:8
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible