clickhouse:
  hosts:
    clickhouse-vm:
      ansible_host: 93.77.176.113
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_rsa

vector:
  hosts:
    vector-vm:
      ansible_host: 93.77.177.52
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_rsa

lighthouse:
  hosts:
    lighthouse-vm:
      ansible_host: 93.77.178.90
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_rsa

all:
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'