---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: ubuntu-podman
    image: ubuntu:latest
    pre_build_image: true
    privileged: true
  - name: oraclelinux-podman
    image: oraclelinux:8
    pre_build_image: true
    privileged: true
provisioner:
  name: ansible
  env:
    ANSIBLE_PIPELINING: "true"
  playbooks:
    prepare: prepare.yml
  inventory:
    group_vars:
      all:
        vector_start_service: false
        vector_version: "0.34.0"
verifier:
  name: ansible